image: ubuntu:latest
stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')
    - ssh dockertest@192.168.56.104 "docker compose up -d" # 192.168.56.104 is the Server-simulation vagrant-machine IP
  tags:
    - docker
  only: 
    - master
